### ISSUE TITLE
Layout issue in Settings page

### ISSUE THREAD

**Issue by topher1kenobe** [easydigitaldownloads/edd-payza#1]
I really have no idea what's going on here, but the layout is funky on the settings page.

<img width="901" alt="screen shot 2016-07-22 at 4 22 23 pm" src="https://cloud.githubusercontent.com/assets/341412/17070209/a33ffcec-5028-11e6-9df1-4956e9404071.png">

**Comment by cklosowski** [comment]
The display of the icon was fixed in EDD Core, but going to change wording to say "Merchant Email" as that's what it really wants. and moving to subsection.
