### ISSUE TITLE
Sorry, but it is not working

### ISSUE THREAD

**Issue by aberniz** [easydigitaldownloads/edd-payza#3]
Hi @pippinsplugins @sandhillsdevelopment @easydigitaldownloads, 

I've installed the Paiza addon for EDD but it is not working. This is the error that shows:
https://projectmanagers.org/wp-content/uploads/2017/09/Paiza-EDD-Integration-Error.jpg

Please, help me.

All the best,
Angel

**Comment by pippinsplugins** [comment]
Hi there!

Please go ahead and open a support ticket through our support portal: https://easydigitaldownloads.com/support

we use GitHub for development tracking only.
