### ISSUE TITLE
Upon checkout, Payza says "Button Configuration is incorrect"

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/edd-payza#8]
When you get to Payza after clicking "complete" on the EDD checkout page, it redirects you to Payza's website with this error message:

`Button configuration is incorrect.`

<img width="1346" alt="screen shot 2017-11-21 at 3 48 33 pm" src="https://user-images.githubusercontent.com/1638128/33096016-913deec0-ced3-11e7-97e0-3149ac27197c.png">

**Comment by cklosowski** [comment]
this is actually a problem with an account that is not in TEST mode.

To test this out properly in your account, you would need to go into your Payza  Business > IPN Configuration and enable test mode, as well as enabling test mode in your Account > API Integration

**Comment by cklosowski** [comment]
To fully test IPN in full test mode, you will need to go to the `Business > Test Center` and get the IPN body, and replay it via postman with the URL:
`<your local site>/index.php?edd-listener=PAYZA_IPN`. Use a POST request and put the full IPN body into the 'Body > Raw' field
